M48
; DRILL file {KiCad 8.0.6} date 2025-08-05T17:05:11-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-05T17:05:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.5039Y-2.9606
T2
X3.8256Y-4.122
M30
